<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LessonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $english=[

                [
                    "id"=> "1",
                    "id_chapter"=> "1",
                    "title"=> "A DAY IN THE LIFE OF",
                    "url"=> "https://s3-ap-southeast-1.amazonaws.com/slearningteam/videos/Bai1.mp4",
                    "des"=> "I. Reading",
                    "url_doc"=> "https=>//drive.google.com/file/d/14kUpJf47oFMECYRagBV2b8omBOkKmbqH/view",
                ],
                [
                    "id"=> "2",
                    "id_chapter"=> "1",
                    "title"=> "A DAY IN THE LIFE OF",
                    "url"=> "https://s3-ap-southeast-1.amazonaws.com/slearningteam/videos/Bai2.mp4",
                    "des"=> "II Listening",
                    "url_doc"=> "https=>//drive.google.com/file/d/14kUpJf47oFMECYRagBV2b8omBOkKmbqH/view",
                ],
                [
                    "id"=> "3",
                    "id_chapter"=> "2",
                    "title"=> "SCHOOL TALKS",
                    "url"=> "https://s3-ap-southeast-1.amazonaws.com/slearningteam/videos/Bai3.mp4",
                    "des"=> "I Reading",
                    "url_doc"=> "https=>//drive.google.com/file/d/1Zc5yghHm2PDuQoK9vsPsWAK8lkiOJW1r/view?usp=sharing",
                ],
                [
                    "id"=> "4",
                    "id_chapter"=> "2",
                    "title"=> "SCHOOL TALKS",
                    "url"=> "https://s3-ap-southeast-1.amazonaws.com/slearningteam/videos/Trailer.mp4",
                    "des"=> "II Listening",
                    "url_doc"=> "https=>//drive.google.com/file/d/1Zc5yghHm2PDuQoK9vsPsWAK8lkiOJW1r/view?usp=sharing",
                ],
                [
                    "id"=> "5",
                    "id_chapter"=> "3",
                    "title"=> "PEOPLE'S BACKGROUND",
                    "url"=> "https://s3-ap-southeast-1.amazonaws.com/slearningteam/videos/Bai1.mp4",
                    "des"=> "I Reading",
                    "url_doc"=> "https=>//drive.google.com/file/d/1ffyNhN1EgXiPTbvUAP1prIlNO9F7lhxS/view?usp=sharing",
                ],
                [
                    "id"=> "6",
                    "id_chapter"=> "3",
                    "title"=> "PEOPLE'S BACKGROUND",
                    "url"=> "https://s3-ap-southeast-1.amazonaws.com/slearningteam/videos/Bai2.mp4",
                    "des"=> "II Listening",
                    "url_doc"=> "https=>//drive.google.com/file/d/1ffyNhN1EgXiPTbvUAP1prIlNO9F7lhxS/view?usp=sharing",
                ],
                [
                    "id"=> "7",
                    "id_chapter"=> "4",
                    "title"=> "SPECIAL EDUCATION",
                    "url"=> "https://s3-ap-southeast-1.amazonaws.com/slearningteam/videos/Bai3.mp4",
                    "des"=> "I Reading",
                    "url_doc"=> "https=>//drive.google.com/file/d/1WFgMU_lIKB9RoyI3tu57cQCflt08Z-Iv/view?usp=sharing",
                ],
                [
                    "id"=> "8",
                    "id_chapter"=> "4",
                    "title"=> "SPECIAL EDUCATION",
                    "url"=> "https://s3-ap-southeast-1.amazonaws.com/slearningteam/videos/Bai1.mp4",
                    "des"=> "II Listening",
                    "url_doc"=> "https=>//drive.google.com/file/d/1WFgMU_lIKB9RoyI3tu57cQCflt08Z-Iv/view?usp=sharing",
                ],
                [
                    "id"=> "9",
                    "id_chapter"=> "5",
                    "title"=> "TECHNOLOGY AN YOU",
                    "url"=> "https://s3-ap-southeast-1.amazonaws.com/slearningteam/videos/Trailer.mp4",
                    "des"=> "I Reading",
                    "url_doc"=> "https=>//drive.google.com/file/d/10R9Q2_ObOPn1wzfAoimGTKoLsM4mqFAG/view?usp=sharing",
                ],
                [
                    "id"=> "10",
                    "id_chapter"=> "5",
                    "title"=> "TECHNOLOGY AN YOU",
                    "url"=> "https://s3-ap-southeast-1.amazonaws.com/slearningteam/videos/Bai3.mp4",
                    "des"=> "II Listening",
                    "url_doc"=> "https=>//drive.google.com/file/d/10R9Q2_ObOPn1wzfAoimGTKoLsM4mqFAG/view?usp=sharing",
                ],
                [
                    "id"=> "11",
                    "id_chapter"=> "6",
                    "title"=> "AN EXCURSION",
                    "url"=> "https://s3-ap-southeast-1.amazonaws.com/slearningteam/videos/Bai2.mp4",
                    "des"=> "I. Reading",
                    "url_doc"=> "https=>//drive.google.com/file/d/1pOyAfDWKR4vhrxgAxl2VAUIEhRWOs1Ti/view?usp=sharing",
                ],
                [
                    "id"=> "12",
                    "id_chapter"=> "6",
                    "title"=> "AN EXCURSION",
                    "url"=> "https://s3-ap-southeast-1.amazonaws.com/slearningteam/videos/Trailer.mp4",
                    "des"=> "II. Listening",
                    "url_doc"=> "https=>//drive.google.com/file/d/1pOyAfDWKR4vhrxgAxl2VAUIEhRWOs1Ti/view?usp=sharing",
                ],
                [
                    "id"=> "13",
                    "id_chapter"=> "7",
                    "title"=> "FRIENDSHIP",
                    "url"=> "https://s3-ap-southeast-1.amazonaws.com/slearningteam/videos/Bai1.mp4",
                    "des"=> "I. Reading",
                    "url_doc"=> "https=>//drive.google.com/file/d/1h5ip8_cvIDiMzygB1xDOGULm7LisCqKW/view?usp=sharing",
                ],
                [
                    "id"=> "14",
                    "id_chapter"=> "7",
                    "title"=> "FRIENDSHIP",
                    "url"=> "https://s3-ap-southeast-1.amazonaws.com/slearningteam/videos/Bai2.mp4",
                    "des"=> "II. Listening",
                    "url_doc"=> "https=>//drive.google.com/file/d/1h5ip8_cvIDiMzygB1xDOGULm7LisCqKW/view?usp=sharing",
                ],
                [
                    "id"=> "15",
                    "id_chapter"=> "8",
                    "title"=> "PERSONAL EXPERIENCES",
                    "url"=> "https://s3-ap-southeast-1.amazonaws.com/slearningteam/videos/Bai3.mp4",
                    "des"=> "I. Reading",
                    "url_doc"=> "https=>//drive.google.com/file/d/1zcVlNnUsPoZYxhavxGcS7xVth_Zek8iN/view?usp=sharing",
                ],
                [
                    "id"=> "16",
                    "id_chapter"=> "8",
                    "title"=> "PERSONAL EXPERIENCES",
                    "url"=> "https://s3-ap-southeast-1.amazonaws.com/slearningteam/videos/Trailer.mp4",
                    "des"=> "II. Listening",
                    "url_doc"=> "https=>//drive.google.com/file/d/1zcVlNnUsPoZYxhavxGcS7xVth_Zek8iN/view?usp=sharing",
                ],
                [
                    "id"=> "17",
                    "id_chapter"=> "9",
                    "title"=> "A PARTY",
                    "url"=> "https=>//www.youtube.com/watch?v=U5Y7Ysr0ro4",
                    "des"=> "I. Reading",
                    "url_doc"=> "https=>//drive.google.com/file/d/1y8bVA6udXZ-av58j7CL_LKmdHPHBMWHF/view?usp=sharing",
                ],
                [
                    "id"=> "18",
                    "id_chapter"=> "9",
                    "title"=> "A PARTY",
                    "url"=> "https=>//www.youtube.com/watch?v=IvdScbu5y6M",
                    "des"=> "II. Listening",
                    "url_doc"=> "https=>//drive.google.com/file/d/1y8bVA6udXZ-av58j7CL_LKmdHPHBMWHF/view?usp=sharing",
                ],
                [
                    "id"=> "19",
                    "id_chapter"=> "10",
                    "title"=> "VOLUNTEER WORK",
                    "url"=> "https=>//www.youtube.com/watch?v=IyR2sHCHYAU",
                    "des"=> "I. Reading",
                    "url_doc"=> "https=>//drive.google.com/file/d/1aBMvq1vplJCyaurAcNC0CvtmThIj7EGq/view?usp=sharing",
                ],
                [
                    "id"=> "20",
                    "id_chapter"=> "10",
                    "title"=> "VOLUNTEER WORK",
                    "url"=> "https=>//www.youtube.com/watch?v=3smMP_5rQcA",
                    "des"=> "II. Listening",
                    "url_doc"=> "https=>//drive.google.com/file/d/1aBMvq1vplJCyaurAcNC0CvtmThIj7EGq/view?usp=sharing",
                ],
                [
                    "id"=> "21",
                    "id_chapter"=> "11",
                    "title"=> "ILLITERACY",
                    "url"=> "https=>//www.youtube.com/watch?v=Gnav8S_Je9U",
                    "des"=> "I. Reading",
                    "url_doc"=> "https=>//drive.google.com/file/d/1y7wgjlkKk5ej0tJ11SNf7U9IPe2y7d7N/view?usp=sharing",
                ],
                [
                    "id"=> "22",
                    "id_chapter"=> "11",
                    "title"=> "ILLITERACY",
                    "url"=> "https=>//www.youtube.com/watch?v=HVDOP-qvTuw",
                    "des"=> "II. Listening",
                    "url_doc"=> "https=>//drive.google.com/file/d/1y7wgjlkKk5ej0tJ11SNf7U9IPe2y7d7N/view?usp=sharing",
                ],
                [
                    "id"=> "23",
                    "id_chapter"=> "12",
                    "title"=> "COMPETITIONS",
                    "url"=> "https=>//www.youtube.com/watch?v=M0Ctx8u58eU",
                    "des"=> "I. Reading",
                    "url_doc"=> "https=>//drive.google.com/file/d/1NRfAt_sPcACojGQAlXW267hDdwYppzAC/view?usp=sharing",
                ],
                [
                    "id"=> "24",
                    "id_chapter"=> "12",
                    "title"=> "COMPETITIONS",
                    "url"=> "https=>//www.youtube.com/watch?v=VSVDslYMUEU",
                    "des"=> "II. Listening",
                    "url_doc"=> "https=>//drive.google.com/file/d/1NRfAt_sPcACojGQAlXW267hDdwYppzAC/view?usp=sharing",
                ],
                [
                    "id"=> "25",
                    "id_chapter"=> "13",
                    "title"=> "HOME LIFE",
                    "url"=> "https=>//www.youtube.com/watch?v=L6EDybuEGIk&t=9s",
                    "des"=> "I. Reading",
                    "url_doc"=> "https=>//drive.google.com/file/d/1hcScaW4WK87qVrf_1ehD6NW3K2nWba3l/view?usp=sharing",
                ],
                [
                    "id"=> "26",
                    "id_chapter"=> "13",
                    "title"=> "HOME LIFE",
                    "url"=> "https=>//www.youtube.com/watch?v=22lGXmuRC6o",
                    "des"=> "II. Listening",
                    "url_doc"=> "https=>//drive.google.com/file/d/1hcScaW4WK87qVrf_1ehD6NW3K2nWba3l/view?usp=sharing",
                ],
                [
                    "id"=> "27",
                    "id_chapter"=> "14",
                    "title"=> "CULTURAL DIVERSITY",
                    "url"=> "https=>//www.youtube.com/watch?v=gO-XArlJMeo",
                    "des"=> "I. Reading",
                    "url_doc"=> "https=>//drive.google.com/file/d/1gvL1cMyoYbLe_EItn343lhh2lArnhivu/view?usp=sharing",
                ],
                [
                    "id"=> "28",
                    "id_chapter"=> "14",
                    "title"=> "CULTURAL DIVERSITY",
                    "url"=> "https=>//www.youtube.com/watch?v=F4OS4BcDL8E",
                    "des"=> "II. Listening",
                    "url_doc"=> "https=>//drive.google.com/file/d/1gvL1cMyoYbLe_EItn343lhh2lArnhivu/view?usp=sharing",
                ],
                [
                    "id"=> "29",
                    "id_chapter"=> "15",
                    "title"=> "WAYS OF SOCIALIZING",
                    "url"=> "https=>//www.youtube.com/watch?v=FI8GyfAFrtk",
                    "des"=> "I. Reading",
                    "url_doc"=> "https=>//drive.google.com/file/d/1hLZBaO5TEA7ach35EwUYyp7Ank2loc-F/view?usp=sharing",
                ],
                [
                    "id"=> "30",
                    "id_chapter"=> "15",
                    "title"=> "WAYS OF SOCIALIZING",
                    "url"=> "https=>//www.youtube.com/watch?v=FI8GyfAFrtk",
                    "des"=> "II. Listening",
                    "url_doc"=> "https=>//drive.google.com/file/d/1hLZBaO5TEA7ach35EwUYyp7Ank2loc-F/view?usp=sharing",
                ],
                [
                    "id"=> "31",
                    "id_chapter"=> "16",
                    "title"=> "SCHOOL EDUCATION SYSTEM",
                    "url"=> "https=>//www.youtube.com/watch?v=aMpNV5CKtzQ",
                    "des"=> "I. Reading",
                    "url_doc"=> "https=>//drive.google.com/file/d/1x4X3S5Pl5zgE0ra-f09NWRnRItE9Anyw/view?usp=sharing",
                ],
                [
                    "id"=> "32",
                    "id_chapter"=> "16",
                    "title"=> "SCHOOL EDUCATION SYSTEM",
                    "url"=> "https=>//www.youtube.com/watch?v=QdWsSgwjuEg",
                    "des"=> "II. Listening",
                    "url_doc"=> "https=>//drive.google.com/file/d/1x4X3S5Pl5zgE0ra-f09NWRnRItE9Anyw/view?usp=sharing",
                ],
                [
                    "id"=> "33",
                    "id_chapter"=> "17",
                    "title"=> "HIGHER EDUCATION",
                    "url"=> "https=>//www.youtube.com/watch?v=DPqS-Nd71R4",
                    "des"=> "I. Reading",
                    "url_doc"=> "https=>//drive.google.com/file/d/1Lo8o23oa3IvslupxoAM8iUsJeps-qRhw/view?usp=sharing",
                ],
                [
                    "id"=> "34",
                    "id_chapter"=> "17",
                    "title"=> "HIGHER EDUCATION",
                    "url"=> "https=>//www.youtube.com/watch?v=TyPf9Z-7mVk",
                    "des"=> "II. Listening",
                    "url_doc"=> "https=>//drive.google.com/file/d/1Lo8o23oa3IvslupxoAM8iUsJeps-qRhw/view?usp=sharing",
                ],
                [
                    "id"=> "35",
                    "id_chapter"=> "18",
                    "title"=> "FUTURE JOBS",
                    "url"=> "https=>//www.youtube.com/watch?v=PBCgZa8yKY8",
                    "des"=> "I. Reading",
                    "url_doc"=> "https=>//drive.google.com/file/d/1wnwbwM6hb8GYvnyIFXD9WcPR-kcOAwvK/view?usp=sharing",
                ],
                [
                    "id"=> "36",
                    "id_chapter"=> "18",
                    "title"=> "FUTURE JOBS",
                    "url"=> "https=>//www.youtube.com/watch?v=7rI45U_36lQ",
                    "des"=> "II. Listening",
                    "url_doc"=> "https=>//drive.google.com/file/d/1wnwbwM6hb8GYvnyIFXD9WcPR-kcOAwvK/view?usp=sharing",
                ],

        ];
        DB::table('Lesson')->insert($english);
    }
}
